spring.application.name=party-service
server.port=8082

# H2 Database (en m\u00e9moire)
spring.datasource.url=jdbc:h2:mem:partydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Actuator (m\u00e9triques pour Prometheus plus tard)
management.endpoints.web.exposure.include=health,info,prometheus
