spring.application.name=stats-service
server.port=8084

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,circuitbreakers,retries

# Resilience4j - Circuit Breaker pour player-service
resilience4j.circuitbreaker.instances.playerService.register-health-indicator=true
resilience4j.circuitbreaker.instances.playerService.sliding-window-size=10
resilience4j.circuitbreaker.instances.playerService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.playerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.playerService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.playerService.permitted-number-of-calls-in-half-open-state=3

# Resilience4j - Retry pour player-service
resilience4j.retry.instances.playerService.max-attempts=3
resilience4j.retry.instances.playerService.wait-duration=500ms
